import Vue from 'vue'
import { 
    Button, 
    Tag,
    Pagination,
    Dialog,
    Menu,
    Submenu,
    MenuItem,
    MenuItemGroup,
    Input,
    InputNumber,
    Radio,
    Select,
    Option,
    OptionGroup,
    DatePicker,
    Breadcrumb,
    Form,
    FormItem,
    Alert,
    Card,
    Header,
    Aside,
    Main,
    Footer,
    Container,
    BreadcrumbItem,
    Table,
    TableColumn,
    Loading
 } from 'element-ui'

Vue.use(Button)
Vue.use(Tag)
Vue.use(Pagination)
Vue.use(Dialog)
Vue.use(Menu)
Vue.use(Submenu)
Vue.use(MenuItem)
Vue.use(MenuItemGroup)
Vue.use(Input)
Vue.use(InputNumber)
Vue.use(Radio)
Vue.use(Select)
Vue.use(Option)
Vue.use(OptionGroup)
Vue.use(DatePicker)
Vue.use(Breadcrumb)
Vue.use(Form)
Vue.use(FormItem)
Vue.use(Alert)
Vue.use(Card)
Vue.use(Header)
Vue.use(Aside)
Vue.use(Main)
Vue.use(Footer)
Vue.use(Container)
Vue.use(BreadcrumbItem)
Vue.use(Table)
Vue.use(TableColumn)
Vue.use(Loading)